### ISSUE TITLE
User story for Researcher

### ISSUE THREAD

**Issue by gjlam95** [IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend#61]
- [ ] Researcher is able to retrieve anonymous data based on the following filters: Location, Subtype, Age, Gender
- [ ] Researcher is able to get minimum, maximum and average of numerical values

**Comment by Zhiyuan-Amos** [comment]
How are we deciding the `location`?

**Comment by gjlam95** [comment]
How about from the `address`? Like contains `bedok` from `bedok reservoir`

**Comment by chk1994** [comment]
Do we need location though? Like Singapore quite small, I dont think living in the East or West makes you more susceptible to heart attack or something haha. But if not I agree address seems to give a good generalization of location

**Comment by Zhiyuan-Amos** [comment]
Can someone else be assigned for deciding `location`? Cos this is an algorithmic thing; no need additional knowledge on the backend to implement. But I think this solution is hard because there are locations like `Fernvale` etc which doesn't contain the location `Seng Kang`.

I wonder if we can make it less user-friendly by allowing the user to select the nearest MRT station or something during registration. So apart from entering the `address` field, the user needs to input a dropdown list of the nearest MRT station.

**Comment by gjlam95** [comment]
@Ley94 any inputs with regards to the discussion?

@Zhiyuan-Amos maybe choose a sector in singapore instead of mrt stations, maybe like north,south,east, or west

**Comment by gjlam95** [comment]
@Ley94 can help to generate fake data and categorise the data (e.g. groups of ages, groups of subtypes) while you wait for backend api?

**Comment by Zhiyuan-Amos** [comment]
How is this issue different from that of [k-anonymity](https://github.com/IFS4205-2018-Sem1-Team1/protect-PM-Lee-frontend/issues/83)?

**Comment by gjlam95** [comment]
I think i created the other one to assign the issue to adeeb. Can bring him into this

**Comment by Zhiyuan-Amos** [comment]
Fake data pls :<

**Comment by gjlam95** [comment]
I come up with the fake data by today!
